- name: Update the machine
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade the machine
  ansible.builtin.apt:
    upgrade: "yes"
    update_cache: true
    force_apt_get: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
