- name: Update the machine
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/rust_vw_pass.yml') }}"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade the machine
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/rust_vw_pass.yml') }}"
  ansible.builtin.apt:
    upgrade: "yes"
    update_cache: true
    force_apt_get: true

- name: Remove dependencies that are no longer required
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/rust_vw_pass.yml') }}"
  ansible.builtin.apt:
    autoremove: true

- name: Check if reboot is required
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/rust_vw_pass.yml') }}"
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
