---
- name: Initial Kali Provisioning
  hosts: kali
  become: true
  packages:
    - name: Update the system
      ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml') }}"
      ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 3600
    - name: Install additional packages
      ansible.builtin.package:
        name: -curl
          -tmuxp
          -protobuf-compiler
          -keepassxc-full
          -luarocks
          -tree-sitter-cli
          -notepadqq
          -putty-tools
          -bloodhound
          -snmp-mibs-downloader
          -libreoffice
          -xxd
          -raven
          -ssh-askpass
          -peass
          -npm
          -shellter
          -proxychains
          -curl
          -dnsrecon
          -enum4linux
          -enum4linux-ng
          -gobuster
          -impacket-scripts
          -nbtscan
          -nikto
          -nmap
          -onesixtyone
          -oscanner
          -redis-tools
          -smbclient
          -smbmap
          -snmpwalk
          -sslscan
          -tnscmd10g
          -whatweb
          -wkhtmltopdf
          -evil-winrm
          -powercat
          -rlwrap
          -2to3
          -bat
          -chisel
          -duf
          -enum4linux
          -exploitdb
          -fdisk
          -file
          -flameshot
          -fzf
          -g++
          -gcc-11
          -gcc-12-base
          -git
          -gnupg
          -gobuster
          -grc
          -grep
          -htop
          -impacket-scripts
          -iputils-ping
          -kate
          -less
          -lsd
          -lua5.4
          -man-db
          -manpages
          -mingw-w64
          -most
          -ncat
          -netcat-traditional
          -nikto
          -nmap
          -nnn
          -onesixtyone
          -open-vm-tools
          -open-vm-tools-desktop
          -openssh-client
          -openvpn
          -python3-dev
          -python3-impacket
          -python3-ldap3
          -python3-pip
          -python3-requests-ntlm
          -python3-setuptools
          -python3-venv
          -python3-yaml
          -remmina
          -ripgrep
          -rlwrap
          -rofi
          -rpm
          -seclists
          -smbclient
          -smbmap
          -snmp
          -sshuttle
          -stow
          -tldr
          -whatweb
          -wine
          -wine64
          -zoxide
          -sipvicious
          -debootstrap
          - fd-find
      state: pres

  Install_Font:
    - name: Create the nerdfont directory
      ansible.builtin.file:
        path: /usr/share/fonts/nerdfonts/
        state: directory
        mode: "0755"

    # Instead of seperate commands to download the archive to downlaods, copy it to the new directory,
    # and decompress, I'm trying the built-in function to do this all under the unarchive commmand
    # - name: Retrieve the nerdfont using http
    #   ansible.builtin.get_url:
    #    url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.tar.xz -o "$font_dir"/CascadiaCode.tar.xz
    #    dest: "/root/Downloads/CascadiaCode.tar.xz"
    #    mode: 655

    # - name: Copy file from downloads to nerdfont folder
    #  ansible.builtin.copy:
    #    src: /root/downloads/CascadiaCode.tar.xz
    #    dest: "/usr/share/fonts/nerdfonts/"
    #    remote_src: yes
    #    owner: root
    #    group: root
    #    mode: "0755"

    - name: Download and Unarchive the nerdfont
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.tar.xz
        dest: "/usr/share/fonts/nerdfonts/"
        remote_src: yes

  Install_rockyou:
    - name: decompress the rockyou archive
      ansible.builtin.unarchive:
        src: /usr/share/wordlists/rockyou.txt.gz
        dest: /usr/share/wordlists/
        # remote_src: yes

  Install AppImages:
    - name: Download nvim
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
        dest: "/opt/nvim"
        mode: 744

  Install Additional packages:
    - name: Create the ligolo directory
      ansible.builtin.file:
        path: /opt/ligolo-ng
        state: directory
        mode: "0755"
    - name: Download and unarchive ligolo
      ansible.builtin.unarchive:
        src: https://github.com/nicocha30/ligolo-ng/releases/download/v0.4.4/ligolo-ng_agent_0.4.4_linux_amd64.tar.gz
        dest: "/opt/ligolo-ng"
        remote_src: yes
