---
- name: Update and upgrade RPIs
  hosts: RPIs
  tasks:
    - name: Simulate long running op (15 sec), wait for up to 45 sec, poll every 5 sec
      ansible.builtin.command: /bin/sleep 15
      async: 45
      poll: 5
  roles:
    - apt_update_rpi

- name: Update and upgrade pihole
  hosts: eddie
  become: true
  tasks:
    - name: Simulate long running op (15 sec), wait for up to 45 sec, poll every 5 sec
      ansible.builtin.command: /bin/sleep 15
      async: 45
      poll: 5
  roles:
    - pihole_up
