- name: Install starship
  community.general.cargo:
    name: "{{ item }}"
    locked: true
  become_user: zippy
  become_method: su
  become_flags: "--login"
  vars:
    ansible_become_pass: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml') }}"
  loop:
    - starship
