- name: Install tigervnc using apt
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/kali.yml') }}"
  ansible.builtin.package:
    name:
      - tigervnc-standalone-server
    state: present

- name: Create the .vnc directory
  ansible.builtin.file:
    path: /home/zippy/.vnc
    state: directory
    owner: zippy
    group: zippy
    mode: "0755"

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /home/sociodicy/scripts/ansible/playbooks/roles/guac_kali/vars/xstartup
    dest: /home/zippy/.vnc
    owner: zippy
    group: zippy
    mode: "0755"

- name: Create a tigervnc Service File
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/kali.yml') }}"
  ansible.builtin.copy:
    src: /home/sociodicy/scripts/ansible/playbooks/roles/guac_kali/vars/vncserver@.service
    dest: /etc/systemd/system/vncserver@.service
    owner: root
    group: root
    mode: "0755"
