# Installing rust and cargo apps
- name: Install dependencies
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml') }}"
  ansible.builtin.package:
    name:
      - rustup
      - build-essential
      - cmake
    state: present

#- name: Install rustup
#  ansible.builtin.script: /home/sociodicy/scripts/ansible/playbooks/roles/rustup/vars/rustup-init.sh -y
#  become: true
#  become_user: zippy
#  become_method: su
#  become_flags: "--login"
#  vars:
#    ansible_become_pass: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml') }}"
- name: Install multiple rust packages
  community.general.cargo:
    name: "{{ item }}"
    locked: true
  become_user: zippy
  become_method: su
  become_flags: "--login"
  vars:
    ansible_become_pass: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml') }}"
  loop:
    - starship
