# Installing rust and cargo apps
- name: Install dependencies
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml') }}"
  ansible.builtin.package:
    name:
      - rustup
      - build-essential
      - cmake
    state: present

- name: Configure rustup app
  ansible.builtin.shell:
    cmd: "rustup default stable"
