# Installing rust and cargo apps
- name: Install dependencies
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vps.yml') }}"
  ansible.builtin.package:
    name:
      - rustup
      - build-essential
      - cmake
    state: present

- name: Configure rustup app
  ansible.builtin.shell:
    cmd: "rustup default stable"
  become: true
  become_user: zippy
  become_method: su
  become_flags: "--login"
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vps.yml') }}"
