- name: Create NFS export directory
  file:
    path: /home/zippy/data
    state: directory
    mode: "0755"

- name: Configure NFS exports
  lineinfile:
    path: /etc/exports
    line: "/home/zippy/data {{ tailscale }}(rw,sync,no_subtree_check)"
    create: true
    state: present
  notify: Restart nfs-kernel-server

- name: Export NFS shares for existing session
  ansible.builtin.command: exportfs -a

- name: Ensure NFS service is running and enabled
  systemd:
    name: nfs-kernel-server
    state: started
    enabled: true
