- name: Install
  ansible.builtin.package:
    name:
      - vim
      - curl
      - git
      - gpg
      - qemu-guest-agent
      - htop
    state: present

- name: Set timezone to Los_Angeles
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml') }}"
  community.general.timezone:
    name: America/Los_Angeles
