# Installing nnn and its plugins using a custom bash script located on z2.
# This script assumes a user named "zippy" exists on the target.
# Using nnn preview on headless machines is very challenging compared to standard rdp, won't be installed here
- name: Install nnn
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/kali.yml') }}"
  ansible.builtin.package:
    name:
      - nnn
      # - xterm
    state: present

- name: Remove the nnn binary
  ansible.builtin.file:
    path: /home/zippy/nnn-nerd-static
    state: absent
