# This role assumes you've already stowed the lazyvim dotfile
- name: Make the destination for stowing lazyvim safe
  ansible.builtin.shell:
    cmd: "git config --global --add safe.directory /home/zippy/.config/nvim"
- name: Clone the lazyvim repo
  ansible.builtin.git:
    repo: "https://github.com/LazyVim/starter"
    dest: /home/zippy/.config/nvim
- name: remove the git directory from the lazyvim repo
  ansible.builtin.file:
    path: /home/zippy/.config/nvim/.git
    state: absent
- name: remove the options.lua file from the neovim directory
  ansible.builtin.file:
    path: /home/zippy/.config/nvim/lua/config/options.lua
    state: absent
- name: remove the keymaps.lua file from the neovim directory
  ansible.builtin.file:
    path: /home/zippy/.config/nvim/lua/config/keymaps.lua
    state: absent
- name: Remove the lazyvim plugins directory
  ansible.builtin.file:
    path: /home/zippy/.config/nvim/lua/plugins
    state: absent
- name: stow lazyvim
  ansible.builtin.shell:
    cmd: "cd /home/zippy/dotfiles && stow lazyvim"
- name: link neovim appimage to /usr/bin
  ansible.builtin.copy:
    src: /home/zippy/nvim
    dest: /home/zippy/.local/bin
    owner: zippy
    group: zippy
    mode: "0755"
    remote_src: true
