- name: Install starship
  community.general.cargo:
    name: "{{ item }}"
    state: latest
  become: true
  vars:
    ansible_become_pass: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml') }}"
  loop:
    - starship
    - dysk
