- name: Install rsyslog
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml') }}"
  ansible.builtin.apt:
    name: rsyslog

- name: Add instruction to dispatch logs to graylog
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml') }}"
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    line: "*.*@@192.168.1.222:514;RSYSLOG_SyslogProtocol23Format"
    regexp: '\*.\*@@192.168.1.222:514;RSYSLOG_SyslogProtocol23Format'
    state: present
    insertafter: EOF
    create: true

- name: Restart rsystlog
  become: true
  vars:
    ansible_become_password: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml') }}"
  ansible.builtin.shell:
    cmd: systemctl restart rsyslog
