- name: Upgrade pi-hole
  ansible.builtin.shell:
    cmd: sudo pihole -up
  vars:
    ansible_become_pass: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vm_pass.yml.yml') }}"
