# Use this playbook whenever you need to update caido
---
- name: Update caido
  hosts: contabo
  become: true
  vars:
    ansible_become_pass: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vps.yml') }}"
  vars_prompt:
    - name: url
      prompt: What is the caido binary download url (found at https://github.com/caido/caido/releases)?
      private: false

    - name: version
      prompt: What is the binary version number (found at https://github.com/caido/caido/releases)?
      private: false

    - name: oldversion
      prompt: What is the previous binary version number (found at https://github.com/caido/caido/releases)?
      private: false

  tasks:
    - name: Download the caido binary
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "/home/zippy/downloads/caido-cli-v{{ version }}-linux-x86_64.tar.gz"
        mode: 755

    - name: Move the old binary to a backup
      ansible.builtin.copy:
        src: "/home/zippy/caido/caido-cli"
        dest: "/home/zippy/caido/caido-cli-{{ oldversion }}.bak"
        owner: zippy
        group: zippy
        mode: 644
        remote_src: true

    - name: Unarchive the caido binary
      ansible.builtin.unarchive:
        src: "/home/zippy/downloads/caido-cli-v{{ version }}-linux-x86_64.tar.gz"
        dest: "/home/zippy/downloads/"
        remote_src: true

    - name: Remove the tar file
      ansible.builtin.file:
        path: "/home/zippy/downloads/caido-cli-v{{ version }}-linux-x86_64.tar.gz"
        state: absent

    - name: Copy file from downloads to caido folder
      ansible.builtin.copy:
        src: "/home/zippy/downloads/caido-cli"
        dest: "/home/zippy/caido/caido-cli"
        remote_src: true
        owner: zippy
        group: zippy
        mode: 0755

    - name: Restart caido service file
      ansible.builtin.systemd_service:
        state: restarted
        name: caido.service
