# Use this playbook whenever you need to update caido
---
- name: Update caido
  hosts: recon
  vars_prompt:
    - name: url
      prompt: What is the caddy binary download url (found at https://github.com/caido/caido/releases)?
      private: false

    - name: version
      prompt: What is the binary version number (found at https://github.com/caido/caido/releases)?
      private: false

  tasks:
    - name: Download the caido binary
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "/home/zippy/downloads/caido-cli-v{{ version }}-linux-x86_64.tar.gz
        mode: 755

- name: Unarchive the caido binary
  become: true
  vars:
    ansible_become_pass: "{{ lookup('ansible.builtin.file', '/home/sociodicy/scripts/ansible/secrets/vps.yml') }}"
  ansible.builtin.unarchive:
    src: "/home/zippy/downloads/caido-cli-v{{ version }}-linux-x86_64.tar.gz"
    dest: "/home/zippy/downloads/"
    remote_src: true

- name: Copy file from downloads to caido folder
  ansible.builtin.copy:
    src: /home/zippy/downloads/caido-cli-v{{ version }}-linux-x86_64.tar.gz
    dest: /home/zippy/caido
    remote_src: true
    owner: zippy
    group: zippy
    mode: "0755"

- name: Reboot lxc
  ansible.builtin.reboot:
    msg: "Rebooting machine in 5 seconds"
