---
# This section does not deal with passwords, and therefore is relevant to lxc.
- hosts: lxc
  tasks:
    - name: Simulate long running op (15 sec), wait for up to 45 sec, poll every 5 sec
      ansible.builtin.command: /bin/sleep 15
      async: 45
      poll: 5
  roles:
    - apt_update_lxc
    - basics_lxc
